/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-variant': 'var(--primary-variant)',
        secondary: 'var(--secondary)',
        'secondary-variant': 'var(--secondary-variant)',
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-variant': 'var(--surface-variant)',
        overlay: 'var(--overlay)',
        'on-primary': 'var(--on-primary)',
        'on-secondary': 'var(--on-secondary)',
        'on-background': 'var(--on-background)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'inverse-surface': 'var(--inverse-surface)',
        'outline-variant': 'var(--outline-variant)',
        outline: 'var(--outline)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: 'var(--error)',
        info: 'var(--info)',
        border: 'var(--border)',
        divider: 'var(--divider)',
        disabled: 'var(--disabled)',
        placeholder: 'var(--placeholder)',
        'error-container': 'var(--error-container)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'primary-container': 'var(--primary-container)',
        tertiary: 'var(--tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-tertiary': 'var(--on-tertiary)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-tint': 'var(--surface-tint)',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'Roboto', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
      },
      boxShadow: {
        sm: '0 1px 3px var(--shadow-color-sm), 0 1px 2px var(--shadow-color-sm-inner)',
        md: '0 4px 6px var(--shadow-color-md), 0 2px 4px var(--shadow-color-md-inner)',
        lg: '0 10px 15px var(--shadow-color-lg), 0 4px 6px var(--shadow-color-lg-inner)',
        inner: 'inset 0 2px 4px var(--shadow-color-inner)',
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      animation: {
        'spin-fast': 'spin 0.7s linear infinite',
        'spin-slow': 'spin 0.8s linear infinite',
        shimmer: 'shimmer 1.5s infinite',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up-mobile': 'slideUpMobile 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-up': 'fadeInUp 0.3s ease both',
        'fade-out-particle': 'fadeOutParticle 0.8s cubic-bezier(0.1, 0.8, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
}
