name: Testando o Runner
run-name: Workflow disparado por ${{ github.actor }}

on: [push]

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh # Avisa para usar o sh em vez do bash que não existe no Alpine
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executando um comando
        run: |
          echo "Se você ler isso no Gitea, o Runner funcionou!"
          node -v
